### ISSUE TITLE
CZI application approval: JupyterHub deployment

### ISSUE THREAD

**Issue by minrk** [jupyter/governance#101]
Like #100, I am writing a proposal for CZI to fund work on collaboration on infrastructure around JupyterHub deployments

The proposal will be submitted by Simula, due May 19.

More info with links to draft documents and prior discussions: https://github.com/jupyterhub/team-compass/issues/403

Let me know if anyone has questions or concerns

**Comment by Carreau** [comment]
Approved for me.

**Comment by minrk** [comment]
Proposal has been submitted.
