### ISSUE TITLE
Permission to use Jupyter/JupyterHub logo in a textbook

### ISSUE THREAD

**Issue by ttimbers** [jupyter/governance#102]
Hi folks! I am creating an image about Jupyter and Git/GitHub for an intro textbook (https://ubc-dsci.github.io/introduction-to-datascience/) we are writing and I want to get permission to use the JupyterHub logo in it. Is this the right place to ask for permission? If not, can you please point me to where I should do this?

**Comment by jasongrout** [comment]
Our trademark usage guidelines are at https://jupyter.org/governance/trademarks.html, and in particular please note the uses that [never require permission](https://jupyter.org/governance/trademarks.html#uses-that-never-require-approval). As noted there, please send an email to the trademarks committee (`jupyter-trademarks@googlegroups.com`) if you have any questions or would like to request permission for your specific case.

**Comment by jasongrout** [comment]
Closing as answered. Thanks!

**Comment by ttimbers** [comment]
Thanks for your prompt response!
