### ISSUE TITLE
[Proposal] - add jupyter/accessibility as a software sub-project

### ISSUE THREAD

**Issue by trallard** [jupyter/governance#124]
Hi y’all

Thanks for all the hard work put into the new governance structure and associated processes.

I had a look at #121, and I am so thrilled to see pathways to acknowledge, formalise, and support long-standing non-code contributions in our ecosystem.

However, looking at this PR also raised several questions/doubts on my end and I will do my best to elaborate here.

Accessibility is listed under the Working Group category in said PR 🎉. However, I wonder why this is not listed under the Software sub-projects. 

As per [https://jupyter.org/governance/software_subprojects.html](https://jupyter.org/governance/software_subprojects.html) the whole [accessibility project](https://github.com/jupyter/accessibility) fits the description and meets most of the requirements for being recognised as a Software SubProject, namely:

- [x]  Adheres to the Jupyter CoC
- [x]  Follows the licensing guidelines - under a [BSD-3 license](https://github.com/jupyter/accessibility/blob/master/LICENSE)
- [x]  Follow Jupyter’s trademark, branding, and intellectual property guidelines.
- [x]  Conduct its activities in a manner that is open, transparent, and inclusive
- [x]  it is already under the [Jupyter GitHub organisation](https://github.com/jupyter/accessibility)

In addition to the criteria for official sub-projects [https://jupyter.org/governance/newsubprojects.html#criteria-for-official-subprojects](https://jupyter.org/governance/newsubprojects.html#criteria-for-official-subprojects):

- [x]  Have an active developer community that offers a sustainable model for future development.
    - Holds regular community calls  and all are properly documented and recorded
    - Leading Jupyter community workshops to raise awareness of accessibility principles and share knowledge and best practices for scientific computing scenarios.
    - High impact decisions and general project updates are shared with the broader Jupyter community through community calls, issues and discussions both on GitHub and Discourse, and attending other projects’ community and projects calls
    - Additionally, folks from the accessibility working group are currently working on the CZI Accessibility grant which is all documented and developed in the open at  https://github.com/Quansight-Labs/jupyter-a11y-mgmt and https://github.com/jupyter/accessibility, plus the team has made an intentional effort to keep the broader community informed on its status and seek feedback along the road (from grant proposal to execution)
- [x]  Use solid software engineering with documentation and tests hosted with appropriate technologies (Read The Docs and GitHub actions are examples of technologies used).
- [x]   Demonstrate continued growth and development.
- [x]  Integrate well with other official sub-projects.
    - This project started as a grassroots advocacy movement. Since its inception, it has focused on building bridges with other projects such as JupyterLab, Jupyter Widgets, and Jupyter notebook, among others.
- [x]  Be developed according to the Jupyter governance and contribution model documented here.
- [x]  Have a well-defined scope.
- [x]  Have an active user community.  
    - To achieve Jupyter’s values of being an inclusive project, we have to ensure accessibility sits at its core. Any improvements in this area positively impact the whole user base of Jupyter and its sub-projects.
    - The above point also implies significant buy-in and collaboration with the sub-projects maintainers
    
Additionally, I know these items are in the works:

- Be packaged using appropriate technologies such as pip, conda, npm, bower, docker, etc. (already present but being improved)
- Maintain a publicly visible Team Compass 

## The ask

I would like to propose incorporating [https://github.com/jupyter/accessibility](https://jupyter.org/governance/newsubprojects.html#proposal-for-incorporation) as a Jupyter official Software sub-project, given that it already satisfies the criteria set for this purpose.

Please note that I am **not proposing replacing the Working group** - I instead believe that these two are complementary to each other since:

1. The whole accessibility area includes significant efforts that fall under the no-code contributions such as:
    1. advocacy and community organisation
    2. education around accessibility, best practices, and disability inclusion
    3. influencing policies and guidelines
        1. technical: best practices for disability inclusion, auditing processes and contribution workflows
        2. documentation aimed at developers around accessibility
        3. DEI (diversity equality and inclusion) - supporting and collaborating with the broader community and the DEI Working Group towards disability inclusion
    4. establishing contribution pathways for disabled users and contributors
    5. bridge the gap between scientific computing and the accessibility community
    6. outreach activities such as conference presentations and workshops organisation
    7. seeking funding to address accessibility issues and barriers
2. It also involves significant code-related work:
    1. Auditing of existing software 
    2. Generation of roadmaps and execution of accessibility improvements
    3. Accessibility testing (both manual and automated)
    4. Direct contributions to the codebase to ensure tools are accessible (mostly to other Jupyter software sub-projects)
    5. Developing tools, workflows, and packages to support and enable the above activities
    

I believe recognising these two branches of accessibility work is the foundation for making progress towards whole inclusion and better serving the global Jupyter community. It is a goal that cannot be done only through advocacy/community work or only through code contributions, to be successful it has to be a multidisciplinary effort.

Also, note I purposely did not follow the process outlined in [https://jupyter.org/governance/newsubprojects.html#proposal-for-incorporation](https://github.com/jupyter/enhancement-proposals), i.e. creating PR against the [https://github.com/jupyter/enhancement-proposals](https://github.com/jupyter/enhancement-proposals) repository since the repository in question is **already** under the Jupyter GitHub organisation. But it is not acknowledged as a software subproject.

If needed, I am happy to go through the formal process of submitting a JEP. But I thought I would raise it first here as an open discussion/question given the project's current status.

**Comment by afshin** [comment]
Hi @trallard! Thank you so much for writing up your reasoning for adding an Accessibility Subproject in addition to the Accessibility Working Group. This is a really helpful document and -- as you note -- there are a couple paths forward.

Do you think you'll be able to make the 4 March governance refactor working group call? It meets on the [regular Zoom channel](https://zoom.us/j/2264645576?pwd=c0JZTHlNdS9Sek9vdzR3aTJ4SzFTQT09) from 17:00-19:00 GMT. We should absolutely talk about this and formulate a plan.

We will post ideas that come out of that conversation in this issue to make sure everyone can track it.

Thanks again; and please come tomorrow if you can!

**Comment by trallard** [comment]
Thanks for the swift response @afshin - I should be able to pop by for the first hour of the call since I have a scheduling conflict for the other hour that I cannot move

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/governance-office-hours-meeting-minutes/1480/178

**Comment by trallard** [comment]
Since we moved forward with the software subproject route and this is now completed, I think this issue should be closed

cc/ @afshin
