### ISSUE TITLE
CZI proposal on documentation and maintenance: steering council approval

### ISSUE THREAD

**Issue by fcollonval** [jupyter/governance#128]
We (QuantStack) are working on a CZI EOSS 5 proposal targeting the documentation and maintenance of JupyterLab v4 & Jupyter Notebook v7.

As discussed 10 days ago, the proposal is focusing on the known and unknown (will happen after the release) challenges relevant to the major technological stack shift of Jupyter Notebook v7 (the backend will be the independent jupyter server and the frontend will be built from JupyterLab plugins).

The draft letter of intent is opened at https://github.com/jupyterlab/team-compass/pull/140.

This request of approval follows the process done for the CZI proposal on accessibility #100. Hence we (QuantStack) would like to request formal approval from the steering council to move forward with this work.

Don't hesitate to comment and to propose changes on the current letter of intent.

**Comment by Carreau** [comment]
+1 from me.

**Comment by fperez** [comment]
👍 too, thanks for putting this out in the open!

**Comment by damianavila** [comment]
+1 as well... IMHO, this is super important for this transitional phase.

**Comment by fcollonval** [comment]
Thanks all for the positive reply and support.

We plan to submit the letter of intent by Friday (Apr. 15th).

**Comment by fcollonval** [comment]
The letter of intent has been submitted - the final version can be seen in the https://github.com/jupyterlab/team-compass/pull/140.

**Comment by fcollonval** [comment]
The letter of intent has been accepted. Time to write the full application.
