### ISSUE TITLE
Rename main branch from master to main ? 

### ISSUE THREAD

**Issue by Carreau** [jupyter/governance#142]
It's a single click in the github UI and will do all the redirect, and will keep this repo consistant with all the others

**Comment by choldgraf** [comment]
I think this is a good idea, moreover I think that Jupyter should encourage the use of `main` over `master` across all of its repositories and organizations. In my opinion, we shouldn't need to seek approval for this change, provided that it doesn't break any major pre-existing PRs or something.

**Comment by Carreau** [comment]
Done.
