### ISSUE TITLE
Terms for use of 3rd party logos on jupyter.org website?

### ISSUE THREAD

**Issue by mrichnu** [jupyter/governance#154]
Hello,

I work at Northwestern University, and a member of our legal team asked me about why Northwestern's logo is displayed on the jupyter.org home page. Normally Northwestern does not allow its logo to be used on 3rd party websites as it implies an endorsement, and in this case the question came up because a peer institution was asking about our being "customers" of Jupyter b/c of the use of our logo.

I know that Jupyter is used heavily around here though so it's not inaccurate exactly to include our logo in the "currently used at" section, but I wonder what terms or process are in use to govern the use of 3rd party logos on your website. 

Thanks,
Matthew

**Comment by Carreau** [comment]
Hello, 

Apologies for the late reply, I'll forward your request to the Jupyter Executive council. 

From what I can tell, this was added in https://github.com/jupyter/jupyter.github.io/pull/35 in 2015  by Nick Timkovich (@nicktimko ) who was at northwestern at the time.

I'll work on removing the logo in the meantime.

**Comment by jasongrout** [comment]
As an update, we removed the logo for now.

**Comment by nicktimko** [comment]
@mrichnu yeah, added it in the PR as @Carreau mentioned way back when I was in the Amaral lab. Did so in good faith following other academic institutions, but if the higher-ups want it gone then so shall it be.
