### ISSUE TITLE
Create an official Jupyter account on Bluesky

### ISSUE THREAD

**Issue by jtpio** [jupyter/governance#168]
Similar to https://github.com/jupyter/governance/issues/146.

Bluesky is getting a lot of traction recently, so it can make sense to have a presence there: https://bsky.app/

It's possible to use a domain name as the handle, so the sign up will hopefully be simpler than Mastodon since there is no instance to choose from. So the Jupyter account could simply use the `@jupyter.org` handle. 

For reference the Bluesky official account is `@bsky.app`:

![image](https://user-images.githubusercontent.com/591645/235139204-ec64a915-469f-4e60-961f-c467ae9726d9.png)

There is no rush to grab a username since it's possible to use a custom domain name. Just opening this issue for awareness.

**Comment by ellisonbg** [comment]
Ping @Ruv7 and @blink1073 from the EC who are working on all things social media.

**Comment by blink1073** [comment]
I requested a Bluesky account using the Jupyter gmail account.  Note: "Bluesky will launch soon. Join the waitlist to try the beta before it's publicly available."

**Comment by ibdafna** [comment]
@blink1073 I have an invite code if needed

**Comment by blink1073** [comment]
Hi @ibdafna, yes, please, we still have not gotten a reply.

**Comment by ibdafna** [comment]
Sent over LinkedIn message!

**Comment by blink1073** [comment]
Thanks @ibdafna, done!

<img width="598" alt="image" src="https://github.com/jupyter/governance/assets/2096628/ee8c4999-add9-43a2-ae3f-aebfc6ebb7c5">

**Comment by ibdafna** [comment]
@blink1073 FYI it's possible to "validate" your identity by adding a TXT record to jupyter.org. Once validated, the handle will be @jupyter.org

**Comment by blink1073** [comment]
Thanks for the heads up, I don't have direct access so I'll bring it up to the EC.  Note to self, instructions are here: https://blueskyweb.xyz/blog/4-28-2023-domain-handle-tutorial

**Comment by RezPs** [comment]
@ibdafna hello man can i ask for a invite code? need it a lot

**Comment by ivanov** [comment]
:broom: cleaning up here and closing this issue.  Looks like this was done. https://bsky.app/profile/projectjupyter.bsky.social

Follow up to ["validate" the account](https://github.com/jupyter/governance/issues/168#issuecomment-1548700207) must have petered  out, so if someone has renewed interest in that, please open a new issue.

Happy hacking! :bowtie:

**Comment by jtpio** [comment]
> Follow up to ["validate" the account](https://github.com/jupyter/governance/issues/168#issuecomment-1548700207) must have petered out, so if someone has renewed interest in that, please open a new issue.

Opened https://github.com/jupyter/governance/issues/257
