### ISSUE TITLE
EC issue follow up

### ISSUE THREAD

**Issue by ericsnekbytes** [jupyter/governance#197]
Here:

- https://github.com/jupyter-governance/ec-team-compass/issues/19

**Comment by Ruv7** [comment]
Thanks Eric! I can't be there at this Thursday's Executive Council office hours but if there are any open questions you can feel free to join that call. Otherwise I can take a look at this next Tuesday or Wednesday when I'll be back from some personal time off.

**Comment by jasongrout** [comment]
We've now merged the docs working group charter. Thanks everyone!
