### ISSUE TITLE
Creating a Project Jupyter GitHub Enterprise Org

### ISSUE THREAD

**Issue by jasongrout** [jupyter/governance#219]
Recently, GitHub offered Jupyter (and other open-source projects) a free upgrade to their [GitHub Enterprise Cloud plan](https://docs.github.com/en/enterprise-cloud@latest/admin/overview/about-github-enterprise-cloud). The basic idea is that Project Jupyter would have an Enterprise org, and inside that enterprise org we have our existing GitHub orgs. The enterprise org provides a place to centrally manage policies and roles across all of the Jupyter GitHub orgs, while still enabling individual subprojects to maintain their individual GitHub orgs.

This upgrade helps solve pain points we've had with multiple GitHub orgs in Jupyter. For example, recently the Jupyter Security subproject enabled 2FA across all of the Jupyter GitHub orgs, and this required a nontrivial amount of work to follow through on each individual GitHub org. With an enterprise org, enabling 2FA across all the Jupyter GitHub orgs would have been single checkbox at the enterprise org level. Also, we've had a tension between creating more orgs to better reflect the autonomy of subprojects and the desire to keep the orgs to a manageable number. A centralized place to manage policies and roles would hopefully resolve that tension, and we can give all subprojects the autonomy of their own GitHub org if desired. As I understand it, the enterprise org also has higher limits for [CI and other resources](https://github.com/pricing).

Based on this information, this last week the Executive Council made the decision to create a [Project Jupyter enterprise org](https://github.com/enterprises/jupyter), and we reached out to the SSC about having various Jupyter GitHub orgs join the enterprise org. At this point, many have joined.

Some of you may have been confused seeing these org invites, or may have seen references to this migration online without more context. We (the EC) apologize for the confusion - we should have opened an issue here first to have better transparency and discussion around this move.

That said, any thoughts or objections to moving all official Jupyter GitHub orgs under the umbrella of the new Jupyter Enterprise org?

**Comment by jasongrout** [comment]
CC @jupyter/executive-council @jupyter/software-steering-council

**Comment by minrk** [comment]
Makes sense, this sounds great! Should membership in the enterprise be part of the subproject docs?

**Comment by fperez** [comment]
@minrk I think that's a good idea - it's also entirely possible that a given subproject might span more than one org (e.g. JupyterLab is complex enough that it could easily decide to give extensions, or jupyter-ai, or something else, its own org). I think this frees us from the org count minimization pressure entirely, and we should let orgs be affiliated to the overall enterprise by tagging which official subproject they belong to very clearly, but without the assumption that one subproject is identical to one org.

**Comment by minrk** [comment]
I think it's worth stating (and perhaps _proposing_) that orgs under Jupyter governance SHOULD or MUST be under the Jupyter enterprise, since I think that's part of what's unclear right now.

**Comment by fperez** [comment]
Fully agreed Min. My personal opinion is that now we have this option, we should use MUST in that language.  That would make it unambiguously clear whether something is or isn't "jupyter official".

**Comment by jasongrout** [comment]
Let's please move new discussion to the new [draft governance change PR](https://github.com/jupyter/governance/pull/221) (i.e., open for discussion and change before voting). I'll close this discussion now that we have a proposal open.
