### ISSUE TITLE
SciPy 2024 conference Jupyter project update

### ISSUE THREAD

**Issue by ivanov** [jupyter/governance#233]
In recent years, [the SciPy Conference](https://www.scipy2024.scipy.org/) has had a Tools Plenary that gives short (~3 minute) talk slots to a bunch of the projects in the ecosystem. Jupyter was again invited to participate this year, and the SciPy conference runs next week, with the Tools Plenary running on each of the three days of talks  (July 10th-12)

Last year, @willingc  and I (@ivanov) gave [the update](https://docs.google.com/presentation/d/1vqz3S5zkTMGPnGt4zAqdcLpeHDioHFJdEXeBKT7RJH0/edit#slide=id.g25923111275_0_95) ( [video](https://youtu.be/Oa8adyUogTw?t=1449) ), and the year prior I believe it was @jasongrout  and @marthacryan ([video](https://www.youtube.com/watch?v=n-0sfx-E_Tw))

Who is coming to SciPy this year and would like to give this update? I will send an email out to get this issue some extra visibility.

Please leave a comment if you'd like to help put together the slides and/or present, but if you just want to indicate that you'll be at SciPy, you can leave a :rocket: reaction. <3

**Comment by rowanc1** [comment]
I will be at SciPy and would love to help out with any announcements about the inclusion of JupyterBook / MyST in the Jupyter Project. We will also (hopefully) be giving a lightning talk about the proceedings, which is running on Curvenote / MyST.

**Comment by choldgraf** [comment]
There are some other MyST/Jupyter Book folks joining as well, and I encourage jupyter people to give them all a friendly hello as newcomers to the jupyter community!

- @agoose77 
- @fwkoch
- @stevejpurves

**Comment by marthacryan** [comment]
I'll also be at SciPy! Definitely want to let others step up but I'll be around to help if needed :)

**Comment by mwcraig** [comment]
I'll be at SciPy and am happy to help. I'm willing to present but also content not to.

**Comment by ivanov** [comment]
@gabalafou did you end up dragging this into "Done" as it was discussed at the SSC working meeting, and did anyone at the meeting want to pitch in to make this presentation happen?

I haven't heard from anyone other than those who chimed in on this issue. I started [a presentation document](https://docs.google.com/presentation/d/1Tkm606t0xq_a_9rj-wjsqisnIzOP7OpggXWME7RXU7E/edit#slide=id.g381764cf08_0_153) in the Jupyter Governance shared drive, but others will have to populate the content, as I have other responsibilities to take care of this week.

**Comment by marthacryan** [comment]
When I was working on this 2 years ago, I remember the toughest part was just getting a concise update from all of the subprojects. Maybe we can tag all of the subprojects and ask them to comment a few bullet points about the last year / what's coming up for them in this thread?

**Comment by jasongrout** [comment]
A thought: maybe the SSC reps can drive the updates from each subproject? (Not that they have to do it themselves, but they can ping people and make sure it gets done?)

**Comment by marthacryan** [comment]
I like that idea! Anyone tagged below: Can you comment a short update on recent updates for the subproject you represent in the SSC? 

@gabalafou (Accessibility), @ivanov (Foundations and Standards), @JohanMabille (Kernels), @jtpio (Frontends), @marthacryan (DEI), @martinRenou (Voilà), @minrk (JupyterHub and Binder), @rpwagner (Security), @SylvainCorlay (Widgets), @vidartf (Server)

**Comment by ivanov** [comment]
I also just sent out another email, this time to the union of councils seeking updates. Anyone who doesn't have access to the presentation yet can just add a comment for what they think should go in the updates here.

**Comment by ivanov** [comment]
An update: we will need slides ready by end of day Thursday, and our talk slot will be on Friday. Those that expressed interest and are the conference have been invited to a private channel on the SciPy2024 conference slack.

**Comment by Ruv7** [comment]
Thanks for coordinating! I added a few slides of content from the EC directly into the deck. The team who is presenting should feel oki to move that content around as the deck starts to get built. Note that the section for technical updates is not meant to be comprehensive, simply a starting point for folks to add highlights from the subprojects.

**Comment by fperez** [comment]
Excellent, thanks @Ruv7!

**Comment by JasonWeill** [comment]
I'm at SciPy, and while I don't have corporate approval from my employer to present this update, I can help prepare it. Met up with @ivanov and @marthacryan, happy to help!

**Comment by Zsailer** [comment]
Hi all, here is a short summary from the jupyter server subproject. Due to the time-sensitive nature here, I wasn't able to run this by the server team. I kept it high level, so it shouldn't been raise any issues from folks. No pressure to use this if you feel it's too late. 

---

Jupyter Server is thriving!

* We meet on [Thursdays, at 8am Pacific on Zoom](https://github.com/jupyter-server/team-compass/issues/57). Come join us and [meet the team](https://jupyter-server-team-compass.readthedocs.io/en/latest/)! Everyone and anyone is welcome to join. 
* This year has been focused on building the [server-side architecture](https://github.com/jupyter-server/jupyter_ydoc) for real-time collaboration (as an extension)! Try it out!

**Comment by manics** [comment]
We've got a few points from JupyterHub on https://github.com/jupyterhub/team-compass/issues/731
feel free to pick/choose/edit if you haven't already

**Comment by ivanov** [comment]
one of the big things that I think should be talked about is the proposed move away from NumFOCUS and to Linux Foundation as a fiscal sponsor, along with a creation of a 501c6 industry tradegroup - which is a vote that's currently under way: https://github.com/jupyter/governance/pull/226

**Comment by ivanov** [comment]
Thank you everyone who pitched and helped us out. [Update delivered!](http://bit.ly/jupyter-2024)

Here's a photos of us at SciPy!
![IMG_7880](https://github.com/user-attachments/assets/42b05e59-051c-4043-9ddb-7020143d6c9b)
