### ISSUE TITLE
Community Call November 13, 2024

### ISSUE THREAD

**Issue by marthacryan** [jupyter/governance#241]
Hey, Jupyter community! We want to see the cool things you’re doing with Jupyter, so the Diversity, Equity, and Inclusion (DEI) standing committee is holding an open call with the community for people to share and chat about their work. Think of it as a “virtual JupyterCon”: It’s a place to announce and share fun things happening in the Jupyter community.

We encourage brief (5 minutes or less) presentations with a demo or screen share, as needed. If you have a GitHub repo or demo web site, please share it!

## Event details
November 13, 2024, at 9:00 AM PST (16:00 UTC; [your timezone](https://arewemeetingyet.com/Los%20Angeles/2024-11-13/9:00/Jupyter%20Community%20Call))
Agenda (add yourself) on [HackMD](https://hackmd.io/Y71c6HqpSliEBb3L_McGfg?both=)
Meet on[ Zoom](https://zoom.us/my/jovyan?pwd=c0JZTHlNdS9Sek9vdzR3aTJ4SzFTQT09)
Anyone can attend, for free! Anyone can present; add yourself to the agenda above. Anyone can sit in on the call. Presenters will lead a demo and spend a few minutes answering questions. Topics will be targeted at a broad Jupyter audience, not just programmers.

Watch previous calls in our [YouTube playlist](https://www.youtube.com/playlist?list=PLUrHeD2K9Cmkoamm4NjLmvXC4Y6E1o8SP).

**Comment by Ruv7** [comment]
Closing this out now as the call was hosted, here is the recording. https://youtu.be/ildFScV6mZQ?feature=shared
