### ISSUE TITLE
Update trademark usage document to reflect issued trademark

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/governance#42]
We have now receive a trademark on the Jupyter logo and should update the trademark usage document to reflect that. Our lawyer recommend the following language be added to usages of the logo:

"®" or "Reg. U.S. Pat. & TM Off." or "Registered in U.S. Patent & Trademark Office."

See also https://github.com/jupyter/jupyter.github.io/issues/250

**Comment by Carreau** [comment]
We should have a non-listed-in-navbar page on jupyter.org that list logos, resources, colors and other things like that.

**Comment by rolweber** [comment]
The section ["How to Use the Trademarks"](https://github.com/jupyter/governance/blob/master/trademarks.md#how-to-use-the-trademarks), in item 0, already mentions that the trademarks are registered. But then it says... "should be accompanied by a symbol for **un**registered trademarks" (emphasis added).

**Comment by Carreau** [comment]
Nice catch ! See https://github.com/jupyter/governance/pull/52

**Comment by lresende** [comment]
The Jupyter logo(s) should also be updated with TM symbol, see external example logo below
![image](https://user-images.githubusercontent.com/382917/65719748-4f625180-e05b-11e9-8a21-b2ae3733a628.png)
