### ISSUE TITLE
License for text of governance document

### ISSUE THREAD

**Issue by njsmith** [jupyter/governance#8]
Hi all,

Can I request that the governance document itself (or perhaps this whole repository for simplicity) be relicensed under something even simpler like like CC-0? Currently it has the standard 3-clause BSD, but I'm actually uncertain how to fulfill those conditions for the numpy governance document (which is a derived work from yours -- https://github.com/numpy/numpy/blob/master/doc/source/dev/governance/governance.rst). The BSD talks about requirements for source and binary distribution (??) and having to include a large notice in our documentation and stuff. It seems inconvenient at best.

Practically speaking I think the mechanism for this would be that everyone who's contributed text would have to say that they agree to the relicensing (if that's true :-)).

**Comment by rgbkrk** [comment]
Creative Commons licensing makes much more sense. I'm :+1: to that. Which one, I have no idea.

**Comment by njsmith** [comment]
CC-BY requires that derived works: "provide the name of the creator and attribution parties, a copyright notice, a license notice, a disclaimer notice, and a link to the material" and "indicate that changes were made".

CC-0 is a public domain dedication: it allows people to do literally anything with the text without restriction.

The other CC licenses start with CC-BY and add extra requirements on top; probably not relevant here.

Each individual has the legal right to pick how they want to license their personal contributions. If some people agree to CC-0 and everyone else agrees to CC-BY, then CC-BY wins.

**Comment by njsmith** [comment]
(Personally I would probably do CC-0, and if you go with that then I plan to license the numpy one under CC-0 too. The goal would be to allow other projects to build off these without the hassle of having to document the full attribution chain.)

**Comment by minrk** [comment]
CC-0 makes the most sense to me. I don't think maintaining a trail of attribution on documents like this is a worthwhile burden.

**Comment by ellisonbg** [comment]
Yep, CC-0 is fine. Nathaniel, do you want to submit a PR?

On Thu, Oct 8, 2015 at 4:13 AM, Min RK <notifications@github.com> wrote:

> CC-0 makes the most sense to me. I don't think maintaining a trail of
> attribution on documents like this is a worthwhile burden.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/governance/issues/8#issuecomment-146452096>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by njsmith** [comment]
I'd be happy to put together a PR, but note that a PR can only record this
change, it can't actually make the change. As a matter of law, a license
change requires explicit assent from everyone who has contributed.
.
So I guess the first thing is to try and put together a list of everyone
who touched the text...

**Comment by ellisonbg** [comment]
Jason is working on this...

On Thu, Oct 8, 2015 at 10:43 AM, Nathaniel J. Smith <
notifications@github.com> wrote:

> I'd be happy to put together a PR, but note that a PR can only record this
> change, it can't actually make the change. As a matter of law, a license
> change requires explicit assent from everyone who has contributed.
> .
> So I guess the first thing is to try and put together a list of everyone
> who touched the text...
> On Oct 8, 2015 6:23 AM, "Brian E. Granger" <notifications@github.com>
> wrote:
>
> > Yep, CC-0 is fine. Nathaniel, do you want to submit a PR?
> >
> > On Thu, Oct 8, 2015 at 4:13 AM, Min RK <notifications@github.com> wrote:
> >
> > > CC-0 makes the most sense to me. I don't think maintaining a trail of
> > > attribution on documents like this is a worthwhile burden.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/jupyter/governance/issues/8#issuecomment-146452096
> >.
> > >
> >
> >
> >
> > --
> > Brian E. Granger
> > Associate Professor of Physics and Data Science
> > Cal Poly State University, San Luis Obispo
> > @ellisonbg on Twitter and GitHub
> > bgranger@calpoly.edu and ellisonbg@gmail.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/jupyter/governance/issues/8#issuecomment-146544051>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/governance/issues/8#issuecomment-146567348>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jasongrout** [comment]
Fixed by #9
