### ISSUE TITLE
CZI: proposal information needed

### ISSUE THREAD

**Issue by trallard** [jupyter/governance#99]
Hi all 

As many of you might be aware a few folks and I are working on a CZI EOSS proposal to tackle accessibility issues in the Jupyter ecosystem. 

In the proposal we have to provide information regarding `Existing support` to the Jupyter ecosystem, esp:

>List active and recent (previous two calendar years) financial or in-kind support for the software project(s), including duration, the amount in USD, and source of funding. Include in this section any previous funding for these software projects received from CZI (maximum of 250 words) 

Since there are 4 proposals being worked on atm I was wondering if there was a way to have this information and share with the rest of the folks working on proposals.

For reference here is the Discourse item where we are keeping track of the proposals:
https://discourse.jupyter.org/t/coordinating-czi-eoss-applications-across-the-community/8472/13 

cc/ @choldgraf @Carreau  and @minrk who I know are the respective PI's in the other proposals

**Comment by Carreau** [comment]
Here are links to two to of the previous  Jupyter Related accepted CZI fundings
 - https://chanzuckerberg.com/eoss/proposals/jupyterhub-contributor-in-residence-program/
 - https://chanzuckerberg.com/eoss/proposals/real-time-collaboration-in-jupyter/

**Comment by trallard** [comment]
@choldgraf do you happen to have the full proposal for the contributor in residence?

From the RTC proposal the figures listed for funding are:

```
Helmsley Charitable Trust: Jupyter Sustainability. $1 million, 2019-2021.
* Alfred P. Sloan foundation grant: Enabling Safe Access to Sensitive Data. $1.68 million 2018-2021
* Eric and Wendy Schmidt and Schmidt Futures grant: Integrated Digital Information System Research.
$2.2 million, 2018-2020.
* Collaboration with employees from Bloomberg, Two Sigma, JP Morgan, Amazon, and others.
* Commercial funding for JupyterLab development from DE Shaw, Goldman Sachs, and others.
* “Jupyter meets the Earth: Enabling discovery in geoscience through interactive computing at scale”
NSF grant for $1.7 million for three years
* Previous six million dollar grant from Leona M. and Harry B. Helmsley Charitable Trust, Gordon and
Betty Moore Foundation, and the Alfred P. Sloan Foundation for four years
```

**Comment by choldgraf** [comment]
@trallard : https://drive.google.com/file/d/1U2r7sZLNn1qC7svzrIrybc5-sK5zWozw/view?usp=sharing

**Comment by choldgraf** [comment]
Hey all - this issue of previous funding has come up a few times, so I've created this Google Sheet to record the ones that I know of right now. It's stored in the JupyterHub team's "proposals and grants" folder, and is editable by anybody on the internet:

https://docs.google.com/spreadsheets/d/1kP1ggTmBji7eGlXYakBfRXKS_I7hjFxKR-gfkh-vO50/edit?usp=sharing

Want to update that list if you learn of anything new, and we can use this as a reference for future proposals as well?

I also opened up a Community Forum topic to share this:

https://discourse.jupyter.org/t/a-co-curated-list-of-funded-grants-gifts-for-the-jupyter-ecosystem/9108

**Comment by ivanov** [comment]
:broom: cleaning up here and closing this issue. 
Happy hacking! :bowtie:
